feat: add change browser modal
WalletConnect/web3inbox pull request #402
Opened 2024-01-15 12:27 UTC by enesozturk

# Description

iOS Chromium browsers don't have `Add to Home Screen` functionality. For the iOS users, we should redirect them to Safari instead. Added change browser modal and refactored conditions for the other modals to make sure that mobile Chroimum users should redirected to Safari first.

# Type of change

- [x] New feature (non-breaking change which adds functionality)

# Fixes/Resolves (Optional)

# Examples/Screenshots (Optional)

<img width="512" alt="Screenshot 2024-01-15 at 15 26 44" src="https://github.com/WalletConnect/web3inbox/assets/19428358/a006e175-0eb8-489d-a76e-2ecf47a51671">

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

# Additional Information (Optional)

Closes https://github.com/WalletConnect/web3inbox-planning/issues/48

2024-01-15 15:10 UTC, chadyj commented
I tested on chrome on desktop, set to the pixel 7, but didn't see the screen as expected

<img width="401" alt="Screenshot 2024-01-15 at 16 09 24" src="https://github.com/WalletConnect/web3inbox/assets/116099/08b8ba86-a157-4996-9f3c-03033704d1b6">

2024-01-15 15:18 UTC, chadyj approved these changes
Tested on an iphone. Works great 👍

2024-01-15 15:25 UTC, devceline commented on src/utils/pwa.ts
> +  browser?.name ? /chrome|crios|edge-chromium/i.test(browser?.name) : false
Should we cover `brave` here?

2024-01-15 15:29 UTC, devceline requested changes
There's a regression.

- On dev tools, switch device to iPhone 
- Open preview
- No `PWA` modal or Change browser modal

2024-01-16 09:57 UTC, devceline approved these changes
LGTM

2024-01-16 10:03 UTC, merged